
pnutstest.class: pnutstest.java
	cp ../../pnuts-1.2/lib/pnuts.jar .
	/usr/java/default/bin/javac -cp pnuts.jar pnutstest.java 

run:
	 /usr/java/default/bin/java -cp pnuts.jar:. pnutstest fib.pnut

clean:
	rm -f *.class pnuts.jar

